[package]
name = "freya-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = { git = "https://github.com/marc2332/freya", rev="c420d95d152cb29698ab26c74102a93ecac1bf1b" }
dioxus = { version = "0.4", features = ["macro", "hooks"] }
itertools = "0.11.0"
serde_json = "1.0.107"
