[package]
name = "freya-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
freya = { git = "https://github.com/marc2332/freya", rev="260403abd13e186e3d0c27057fd3508cb19ddaa6" }
dioxus = { version = "0.4", features = ["macro", "hooks"] }
itertools = "0.11.0"
serde_json = "1.0.107"
